#!/bin/bash
#
#######################################
# Installs all required dependencies for Cassandra streaming server app
# Globals:
#   None
# Arguments:
#   None
# Returns:
#   None
#######################################
#
# Cassandra Installation Script
# Reference: http://cassandra.apache.org/download/
#

PARENT_PATH=$( cd "$(dirname "${BASH_SOURCE[0]}")"; pwd -P )
NGINX_RTMP_IP="${NGINX_RTMP_IP:-35.239.238.204}"
NGINX_RTMP_PORT="${NGINX_RTMP_PORT:-19350}"
CERT_PATH="/etc/ssl/certs"
CERT_FILE_ADDRESS="${CERT_FILE_ADDRESS:-127.0.0.1:8000/meowl_nginx.crt}"
STUNNEL_CONF_FILE="foreground = yes
debug = 5

[my-encryption-service]
client = yes
accept = 1234
connect = ${NGINX_RTMP_IP}:${NGINX_RTMP_PORT}
CAfile = ${CERT_PATH}/meowl_nginx.crt
verify = 3"

# Install python driver
install_python_driver() {
  sudo apt-get -y install librtmp-dev
  sudo apt-get -y install stunnel4
  cd ${PARENT_PATH}
  python3 -m venv venv
  source ./venv/bin/activate
  pip install --upgrade pip
  pip install -r requirements.txt
}

# Pastes stunnel configs to stunnel.conf
create_stunnel_config_file() {
  echo "${STUNNEL_CONF_FILE}" | sudo tee /etc/stunnel/stunnel.conf
}

# Downloads cert from file address
get_cert() {
  wget -O ${CERT_PATH}/meowl_nginx.crt ${CERT_FILE_ADDRESS} 
}


# Complete Installation for Cassandra Streaming Server app
install_cassandra() {
  echo "Installing Cassandra storing stream app..."
  sudo apt-get update
  install_python_driver
  create_stunnel_config_file
  get_cert
}

install_cassandra
