#!/bin/bash
#
#######################################
# Installs all required dependencies for Meowl notification server
# Globals:
#   None
# Arguments:
#   None
# Returns:
#   None
#######################################
PARENT_PATH=$(
  cd "$(dirname "${BASH_SOURCE[0]}")"
  pwd -P
)

# Install Node.js on Arch Linux
install_node() {
  command -v node >/dev/null 2>&1 || {
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash
    source ~/.nvm/nvm.sh
    nvm install 12.15.0
  }
}

# Install dependencies for notification folder
init_notif() {
  cd ${PARENT_PATH} && npm install && cd -
}

#Install node and initializes configuration for Node related apps
install_notif() {
  echo "Installing node and download npm-packages for notifications app..."
  install_node
  init_notif
}

install_notif