#!/bin/bash
#
#######################################
# Installs all required dependencies to install OpenCV app
# Globals:
#   None
# Arguments:
#   None
# Returns:
#   None
#######################################

PARENT_PATH=$(
  cd "$(dirname "${BASH_SOURCE[0]}")"
  pwd -P
)
NGINX_RTMP_IP=${NGINX_RTMP_IP:-192.168.1.10}
NGINX_RTMP_PORT=${NGINX_RTMP_PORT:-8000}

CERT_PATH="/etc/ssl/certs"
CERT_FILE_ADDRESS=${CERT_FILE_ADDRESS:-127.0.0.1:8008/meowl_nginx.crt}
STUNNEL_PORT=${STUNNEL_PORT:-1234}
STUNNEL_CONF_FILE="foreground = yes
debug = 5

[my-encryption-service]
client = yes
accept = ${STUNNEL_PORT}
connect = ${NGINX_RTMP_IP}:${NGINX_RTMP_PORT}
CAfile = ${CERT_PATH}/meowl_nginx.crt
verify = 3"

# Pastes stunnel configs to stunnel.conf
create_stunnel_config_file() {
  echo "${STUNNEL_CONF_FILE}" | sudo tee /etc/stunnel/stunnel.conf
}

# Downloads cert from file address
get_cert() {
  wget -O ${CERT_PATH}/meowl_nginx.crt ${CERT_FILE_ADDRESS} 
}

install_python_driver(){
  sudo apt install -y python3-pip
  sudo apt install -y python3-venv
  sudo apt-get install -y stunnel4
  cd ${PARENT_PATH}
  python3 -m venv venv
  source venv/bin/activate
  pip3 install -r requirements.txt
}

# Install opencv and related dependencies
install_opencv() {
  echo "Installing Meowl OpenCV App..."
  sudo apt -y update
  install_python_driver
  create_stunnel_config_file
  get_cert
}

install_opencv
