#!/bin/bash
PARENT_PATH=$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd -P)
cd /usr/local/kafka && ./bin/zookeeper-server-start.sh config/zookeeper.properties &
cd /usr/local/kafka && ./bin/kafka-server-start.sh config/server.properties &
cd /usr/local/kafka && ./bin/kafka-topics.sh --create --bootstrap-server localhost:9092 \
  --replication-factor 1 --partitions 1 --topic notif
npm start --prefix ${PARENT_PATH}/notifications