#!/bin/bash
cd /usr/local/kafka && ./bin/zookeeper-server-start.sh config/zookeeper.properties &
cd /usr/local/kafka && ./bin/kafka-server-start.sh config/server.properties &
cd /usr/local/kafka && ./bin/kafka-topics.sh --create --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic notif
cd notifications && npm start &