#!/bin/bash
#
#######################################
# Installs all required dependencies to install Cassandra 
# Globals:
#   None
# Arguments:
#   None
# Returns:
#   None
#######################################
#
# Cassandra Installation Script
# Reference: http://cassandra.apache.org/download/
#

PARENT_PATH=$( cd "$(dirname "${BASH_SOURCE[0]}")"; pwd -P )

# Modify server hostname for connection
modify_server_hostname() {
  echo "Modifying server hostname..."
  sudo sed -i 's/# JVM_OPTS="$JVM_OPTS -Djava.rmi.server.hostname=<public name>"/JVM_OPTS="$JVM_OPTS -Djava.rmi.server.hostname=127.0.0.1"/' /etc/cassandra/cassandra-env.sh
}

# Complete Installation for Cassandra
install_cassandra() {
  sudo apt-get update
  echo "Adding Cassandra repository to system..."
  echo "deb http://www.apache.org/dist/cassandra/debian 311x main" | sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list
  echo "Adding the Apache Cassandra repository keys..."
  wget -q -O - https://www.apache.org/dist/cassandra/KEYS | sudo apt-key add -
  sudo apt-get update
  echo "Installing Cassandra..."
  sudo apt-get -y install cassandra
  modify_server_hostname
}

install_cassandra
