#! /bin/bash
PARENT_PATH=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )

RANDOM_STRING=$(head /dev/urandom | tr -dc _A-Z-a-z0-9 | head -c 32 ; echo '')
export RASPBERRY_PI_FLASK_SECRET_KEY=${RANDOM_STRING}
export SERVER_RTMP_URL_LINK="rtmp://192.168.1.15:8080/show/stream"
export PYTHONPATH="${PYTHONPATH}:${PARENT_PATH}"

source ${PARENT_PATH}/venv/bin/activate
python3 ${PARENT_PATH}/meowlpi/app.py
