#! /bin/bash
PARENT_PATH=$(cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
source ${PARENT_PATH}/venv/bin/activate
export PYTHONPATH="${PYTHONPATH}:${PARENT_PATH}"
export SERVER_RTMP_URL_LINK=""
export RASPBERRY_PI_FLASK_SECRET_KEY="testing"
pytest -s
