#!/bin/bash

INSTALLATION_HELP_TEXT="Usage: install.sh [SERVICE]...
Install SERVICE(s) required for Meowl
With no arguments, install all required services"

# Installing all the required dependencies based on the arguments provided
# If there's no arguments install all the dependencies that Meowl needs
if [[ $# -eq 0 ]]; then
  source ./lib/install_minikube.sh
  install_kubernetes
  source ./lib/install_kafka.sh
  install_kafka
  source ./lib/install_node.sh
  install_node_all
  source ./lib/install_opencv.sh
  install_opencv
  source ./lib/install_nginx_rtmp.sh
  install_nginx_with_rtmp
else
  for arg in "$@"; do
    case ${arg} in
    kubernetes)
      source ./lib/install_minikube.sh
      install_kubernetes
      ;;
    kafka)
      source ./lib/install_kafka.sh
      install_kafka
      ;;
    node)
      source ./lib/install_node.sh
      install_node_all
      ;;
    opencv)
      source ./lib/install_opencv.sh
      install_opencv
      ;;
    nginx-rtmp)
      source ./lib/install_nginx_rtmp.sh
      install_nginx_with_rtmp
      ;;
    --help | -help | -H)
      echo "${INSTALLATION_HELP_TEXT}"
      ;;
    *)
      echo "install.sh: Unknown argument ${arg}"
      ;;
    esac
  done
fi
echo "Successfully installed the dependencies"
