#!/bin/bash

INSTALLATION_HELP_TEXT="Usage: install.sh [SERVICE]...
Install SERVICE(s) required for Meowl
With no arguments, install all required services"

# Installing all the required dependencies based on the arguments provided
# If there's no arguments install all the dependencies that Meowl needs
if [[ $# -eq 0 ]]; then
  ./lib/install_minikube.sh
else
  for arg in "$@"; do
    case ${arg} in
    kubernetes)
      ./lib/install_minikube.sh
      ;;
    kafka)
      ./lib/install_kafka.sh
      ;;
    --help | -help | -H)
      echo "${INSTALLATION_HELP_TEXT}"
      ;;
    *)
      echo "install.sh: Unknown argument ${arg}"
      ;;
    esac
  done
fi
echo "Successfully installed the dependencies"
