#!/bin/bash
#
#######################################
# Installs all required dependencies of Meowl based on arguments provided
# Globals:
#   None
# Arguments:
#   $@ - Name of the service or server to install all server dependencies
# Returns:
#   None
#######################################

INSTALLATION_HELP_TEXT="Usage: install.sh [SERVICE]...
Install SERVICE(s) required for Meowl"

# Installing all the required dependencies based on the arguments provided
meowl_install() {
  for arg in "$@"; do
    PARENT_PATH=$(
      cd "$(dirname "${BASH_SOURCE[0]}")"
      pwd -P
    )
    case ${arg} in
    kubernetes)
      source ${PARENT_PATH}/lib/install_minikube.sh
      install_kubernetes
      ;;
    kafka)
      source ${PARENT_PATH}/lib/install_kafka.sh
      install_kafka
      ;;
    cassandra)
      source ${PARENT_PATH}/lib/install_cassandra.sh
      install_cassandra
      ;;
    mobile)
      source ${PARENT_PATH}/lib/install_mobile.sh
      install_mobile_dev
      ;;
    node)
      source ${PARENT_PATH}/lib/install_node.sh
      install_node_all
      ;;
    opencv)
      source ${PARENT_PATH}/lib/install_opencv.sh
      install_opencv
      ;;
    nginx-rtmp)
      source ${PARENT_PATH}/lib/install_nginx_rtmp.sh
      install_nginx_rtmp_all
      ;;
    server)
      meowl_install kubernetes
      meowl_install kafka
      meowl_install cassandra
      meowl_install node
      meowl_install opencv
      meowl_install nginx-rtmp
      ;;
    raspberry-pi)
      source ${PARENT_PATH}/lib/install_raspberry_pi.sh
      install_raspberry_pi
      ;;
    --help | -help | -H)
      echo "${INSTALLATION_HELP_TEXT}"
      ;;
    *)
      echo "install.sh: Unknown argument ${arg}"
      ;;
    esac
  done
}

meowl_install "$@"
