#!/bin/bash
#
#######################################
# Installs all required dependencies of Meowl based on arguments provided
# Globals:
#   None
# Arguments:
#   $@ - Name of the service or server to install all server dependencies
# Returns:
#   None
#######################################

INSTALLATION_HELP_TEXT="Usage: install.sh [SERVICE]...
Install SERVICE(s) required for Meowl"

# Installing all the required dependencies based on the arguments provided
meowl_install() {
  if [ $# -eq 0 ]
  then
    echo "No arguments supplied..."
  fi
  for arg in "$@"; do
    PARENT_PATH=$(
      cd "$(dirname "${BASH_SOURCE[0]}")"
      pwd -P
    )
    case ${arg} in
    kubernetes)
      source ${PARENT_PATH}/lib/kube/install
      ;;
    kafka)
      source ${PARENT_PATH}/lib/kafka/install
      ;;
    cassandra)
      source ${PARENT_PATH}/lib/cassandra/install
      ;;
    mobile-dev)
      source ${PARENT_PATH}/camera/mobile/install
      ;;
    notifications)
      source ${PARENT_PATH}/notifications/install
      ;;
    opencv)
      source ${PARENT_PATH}/cv/install
      ;;
    nginx-rtmp)
      source ${PARENT_PATH}/lib/nginx-rtmp/install
      ;;
    server)
      meowl_install kubernetes
      meowl_install kafka
      meowl_install cassandra
      meowl_install node
      meowl_install opencv
      meowl_install nginx-rtmp
      ;;
    raspberry-pi)
      source ${PARENT_PATH}/camera/pi/install
      ;;
    web)
      source ${PARENT_PATH}/web/install
      ;;
    --help | -help | -H)
      echo "${INSTALLATION_HELP_TEXT}"
      ;;
    *)
      echo "install.sh: Unknown argument ${arg}"
      ;;
    esac
  done
}

meowl_install "$@"
